### PR TITLE
Stop monkey patching `Object` when including `safely_block`

### PR DESCRIPTION
**Pull request by zspencer**
Part of #175

### CODE REVIEW

**Comment by ankane** [comment]
Thanks @zspencer, it's been on my todo list.  Instead of including `Safely::Methods`, can we instead use `Safely.safely`?

**Comment by zspencer** [comment]
@ankane done!

**Comment by ankane** [comment]
Great, thanks again! 💯

**Comment by zspencer** [comment]
@ankane do  you know if / when you'll do a release of this? Or should we live off of a checkout for a bit?

**Comment by ankane** [comment]
I'm not planning to do a release for this, but you can point your Gemfile to master.

**Pull request merged**
