### PR TITLE
Handle invalid UTF-8 bytes in User-Agent

### PR DESCRIPTION
**Pull request by jughead**

### CODE REVIEW

**Comment by ankane** [comment]
Hey @jughead, thanks for another PR 👍 What's the best way to manually test this / reproduce the current issue?

**Comment by jughead** [comment]
screen shot 2018-04-06 at 21 43 20
☝️ ✅

**Comment by jughead** [comment]
Just any request with invalid user agent. I run the server and then performed the test request:
```
http = Net::HTTP.new('localhost', '3000')
request = Net::HTTP::Post.new('/ahoy/visits')
request['User-Agent'] = "\xF1\x61\x3b\x46"
request.set_form_data({"visit_token":SecureRandom.uuid,"visitor_token":SecureRandom.uuid,"platform":"Web","landing_page":"https://www.blabla.com/blabla","screen_width":320,"screen_height":568,"js":true,"referrer":"http://m.facebook.com"})
http.request(request)
```
I then received the following error:
```
PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xf1 0x61 0x3b 0x46
: INSERT INTO "visits" ("id", "visitor_id", "ip", etc...
```

**Comment by jughead** [comment]
Configuration:
```
Ahoy.api = true
Ahoy.server_side_visits = :when_needed
Safely.report_exception_method = Proc.new { |err| Rails.logger.error(err) }
```

**Comment by ankane** [comment]
Great, thanks @jughead 💯

**Pull request merged**
