### PR TITLE
add configuration and docs to use alternatives to RequestStore

### PR DESCRIPTION
**Pull request by saturnflyer**
I'm using an alternative to RequestStore from https://github.com/ElMassimo/request_store_rails

These changes allow you to set the module's `request_store` to something different.

``` ruby
Ahoy.request_store = RequestLocals
```

Without these changes I'd need to do something like `Object.const_set(:RequestStore, RequestLocals)` to get it to work with the alternative. It made sense to have it be configurable however.

I want to add tests but I don't know what pattern to follow. Is there currently any plan to add more tests to this gem? Can you point me in the right direction? Or is that something I can help do in other PRs?

### CODE REVIEW

**Comment by ankane** [comment]
Hey @saturnflyer, thanks for the PR. However, I don't see much value in supporting multiple request stores. Is there a benefit to using `request_store_rails`?

**Comment by saturnflyer** [comment]
@ankane The problem is listed here https://github.com/ElMassimo/request_store_rails#the-problem where the author says that using `request_store` "does not work when you need to use multiple threads per request, different threads access different stores."

**Comment by saturnflyer** [comment]
I've rebased the commits and simplified them.

Without these changes I am required to use 2 implementations of a request store because Ahoy has a specific dependency separate from what I want in my application. With these change I only need to set up Ahoy to use an equivalent storage.
It appears to me that Ahoy merely requires that some request store behave in the appropriate way and it will work properly and not that it _must_ be the `request_store` gem.

**Comment by saturnflyer** [comment]
This PR will need an update if it goes forward. RequestStore has methods such as `end!` which RequestLocals (provided by request-store-rails) does not. I'm not sure if Ahoy uses that method or another dependency but I wanted to add this comment here for anyone else interested.

The implementation of request-store uses `Thread.current` and request-store-rails uses `ThreadSafe::Cache.new` from the concurrent_ruby gem.

For anyone else reading and interested, here's what I'm currently putting at the top of my `config/initializers/ahoy.rb`
```ruby
require 'request_locals'
STDOUT.puts "Overriding RequestLocals to match RequestStore and work with Ahoy"

RequestLocals.instance_eval do
  def begin!
    @cache[:request_store_active] = true
  end

  def end!
    @cache[:request_store_active] = false
  end

  def active?
    @cache.fetch(:request_store_active, false)
  end
end

RequestStore = RequestLocals
```

**Comment by ankane** [comment]
Going to close as well - see #130.

**Pull request closed without merging**
