### PR TITLE
Added amp_analytics helper

### PR DESCRIPTION
**Pull request by Bahanix**
Cf. https://github.com/ankane/ahoy/issues/335

Tell me if you want any changes :)

### CODE REVIEW

**Comment by ankane** [comment]
Thanks @Bahanix 👍 Working on getting Ahoy 2.0 out tonight or tomorrow. Will dig into this sometime this week.

**Comment by ankane** [comment]
Hey @Bahanix, it looks like there's an [amp-analytics](https://www.ampproject.org/docs/guides/analytics/analytics_basics) component that's more powerful and may not require opening a GET endpoint (can use XHR or sendBeacon). Do you have any experience with that?

**Comment by Bahanix** [comment]
No experience but it seems to be totally feasible. I'll give it a try and update PR accordingly.

**Comment by geo1004** [comment]
Thanks a lot @Bahanix

**Comment by Bahanix** [comment]
I (finally!) updated the PR :tada:

**Comment by ankane** [comment]
Hey @Bahanix, thanks for updating 👍 Overall, it's a great foundation. I made a few changes on the `amp` branch here: https://github.com/ankane/ahoy/commit/b61273ec90f5ad4c00e794622af42c7bd8f44ff3

1. Switched to the events endpoint since pageviews are events. As part of this, changed the helper interface to match the events interface: `amp_event(name, properties)`
2. Since AMP pages can be cached, it's better to use `${clientId(site-user-id)}` instead of the Ahoy tokens. https://www.ampproject.org/docs/analytics/analytics_basics
3. Use `ActionController::Base.default_url_options` to get the host, as it's safer than getting it from the request
4. Use the `visible` event instead of `ini-load`, as most examples I found used this

Let me know your thoughts on the changes.

**Comment by Bahanix** [comment]
1. I am only interrested by visits and do not use events, is it compatible with the `amp_event` helper ? I could manage 
2. ✔️ 
3. ✔️ 
4. I was using `ini-load` because I had some trouble to trigger the `visible` event, but I just tried it with the `amp` branch again and it works very well with `visible`: ✔️

**Comment by ankane** [comment]
Just merged. Thanks for adding this 👍

**Pull request merged**
