### PR TITLE
Add httponly config flag & functionality

### PR DESCRIPTION
**Pull request by piousbox**
httponly is a cookie attribute that increases security of the application

### CODE REVIEW

**Comment by ankane** [comment]
Hey @piousbox, can you add a description?

**Comment by piousbox** [comment]
I looked at the failing CI check, but don't know off the top of my head what causes it. The functionality is manually tested, works in production.

**Comment by ankane** [comment]
Hey @piousbox, thanks for the PR, but unfortunately, I don't think it's needed.

**Comment by charusat09** [comment]
Hey @ankane, HttpOnly cookie flag is certainly required. The reasons are two-fold. First, it enhances security as the author of this PR said. Second, many at least TrustWare PCI scanner required HttpOnly cookie test pass. Our application was continuously failing for this test so, we removed ahoy gem for a while. Thanks.

**Pull request closed without merging**
