### PR TITLE
Add immediate event tracking with navigator.sendBeacon

### PR DESCRIPTION
**Pull request by vaihtovirta**
Hello!
My PR partially related to #87 
In my application I'm trying to track time that user spends on page. Ahoy works fine if user navigate over website. But there is no way to track time if user, for example, closes browser tab. Possible solution is to use [navigator.sendBeacon](https://developer.mozilla.org/ru/docs/Web/API/Navigator/sendBeacon) method and send event data inside 'unload' or 'beforeunload' event callback. Although it is not supported in IE/Safari and it is experimental feature, it can be helpful in some cases.
Here is the simple example (we should pass `true` for the last argument to perform immediate tracking):

```
var startTime = performance.now();

window.addEventListener('beforeunload', trackTime, false);

function trackTime(event) {
  var endTime = performance.now();
  ahoy.track('Spent time', { time: endTime - startTime }, true);
}
```

I've added extra argument to `ahoy.track` and simple check for `navigator.sendBeacon` support.
If this PR should be reopened in ahoy.js repo, please let me know.
Thank you.

### CODE REVIEW

**Comment by vaihtovirta** [comment]
Hi there! I've added polyfill, so it will be possible to use Navigator.sendBeacon() in browsers that don't support it natively.

p.s. Still hope to get any feedback about this :smiley:

**Comment by ACPK** [comment]
+1

**Comment by ankane** [comment]
Hey @vaihtovirta, thanks for the PR, and sorry for not following up earlier. I like the idea of being able to send events immediately.  If we can reliably do so in all browsers, we should make it the default rather than adding an option for it.  However, I'm not sure the polyfill does anything differently than jQuery's `$.post` method, which means this still wouldn't work in a decent percentage of browsers.

**Comment by ankane** [comment]
Ahoy.js now has an option for this.

**Pull request closed without merging**
