### PR TITLE
Adding Ahoy.cookie_options to provide support for same site

### PR DESCRIPTION
**Pull request by zachhweed**
Hey all, first contribution to this repo so let me know if I missed anything. This is to support a new attribute of `Ahoy`: `cookie_options`. This was added to support SameSite, but it was kept open enough to allow for further extension. All of that being said I have a feeling this may be a tad too simple. If that's the case just let me know and I'll get some more work done on it.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @zachhweed, thanks for the PR!

I believe the `merge` line is a no-op since it's not saving the result back to `cookie`. I think you'll want something like `cookie = Ahoy.cookie_options.merge(value: value)`. Also, let's move the `mattr_accessor` code to be with the other cookie options.

**Comment by zachhweed** [comment]
Thanks @ankane. Just for clarification, did you want me to move the `mattr_accessor` below line `33` like so:

```
  mattr_accessor :cookies
  self.cookies = true

  mattr_accessor :cookie_domain

  mattr_accessor :cookie_options
  self.cookie_options = {}
```

Or did you want me to move it between files? Thanks again.

**Comment by ankane** [comment]
Yeah, like you have it above (same file).

**Comment by ankane** [comment]
Looks great, thanks @zachhweed!

**Comment by willianveiga** [comment]
When will this feature be released?

**Pull request merged**
