### PR TITLE
Update logger_silencer for Rails 5 Compatibility

### PR DESCRIPTION
**Pull request by codebreach**
Copied from https://github.com/rails/activerecord-session_store/blob/master/lib/active_record/session_store/extension/logger_silencer.rb to pull in rails 5 compatibility updates

### CODE REVIEW

**Comment by ankane** [comment]
Thanks for the pull request Madhav! The current implementation should work with Rails 5.

**Comment by ckassen** [comment]
Implementation in 1.3.0 breaks with Rails 4.2.6, pulling in the latest changes from activerecord-session_store fixes this.

**Comment by ckassen** [comment]
@ankane I can only pull it from Rollbar, as I have completely disabled the ahoy log silencer, but here it is:

```
NoMethodError: undefined method `[]' for nil:NilClass

File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/logger_silence.rb" line 23 in level
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/ahoy_matey-1.3.0/lib/ahoy/logger_silencer.rb" line 28 in add
File "/usr/lib/ruby/2.3.0/logger.rb" line 507 in error
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/log_subscriber.rb" line 85 in rescue in finish
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/log_subscriber.rb" line 83 in finish
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/fanout.rb" line 102 in finish
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/fanout.rb" line 46 in block in finish
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/fanout.rb" line 46 in each
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/fanout.rb" line 46 in finish
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb" line 36 in finish
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb" line 25 in instrument
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb" line 466 in log
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 154 in execute
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/schema_statements.rb" line 286 in client_min_messages=
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb" line 673 in configure_connection
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb" line 658 in connect
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb" line 242 in initialize
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb" line 44 in new
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb" line 44 in postgresql_connection
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb" line 438 in new_connection
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb" line 448 in checkout_new_connection
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb" line 422 in acquire_connection
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb" line 349 in block in checkout
File "/usr/lib/ruby/2.3.0/monitor.rb" line 214 in mon_synchronize
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb" line 348 in checkout
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb" line 263 in block in connection
File "/usr/lib/ruby/2.3.0/monitor.rb" line 214 in mon_synchronize
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb" line 262 in connection
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb" line 571 in retrieve_connection
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb" line 113 in retrieve_connection
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_handling.rb" line 87 in connection
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/query_cache.rb" line 51 in restore_query_cache_settings
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/query_cache.rb" line 43 in rescue in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/query_cache.rb" line 31 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb" line 653 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb" line 29 in block in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb" line 88 in __run_callbacks__
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb" line 778 in _run_call_callbacks
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb" line 81 in run_callbacks
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb" line 27 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb" line 78 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/rollbar-2.8.2/lib/rollbar/middleware/rails/rollbar.rb" line 24 in block in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/rollbar-2.8.2/lib/rollbar.rb" line 948 in scoped
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/rollbar-2.8.2/lib/rollbar/middleware/rails/rollbar.rb" line 22 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb" line 17 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/rollbar-2.8.2/lib/rollbar/middleware/rails/show_exceptions.rb" line 22 in call_with_rollbar
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb" line 30 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/lograge-0.3.6/lib/lograge/rails_ext/rack/logger.rb" line 15 in call_app
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb" line 20 in block in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb" line 68 in block in tagged
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb" line 26 in tagged
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb" line 68 in tagged
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/rack/logger.rb" line 20 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/ahoy_matey-1.3.0/lib/ahoy/log_silencer.rb" line 12 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/request_store-1.3.0/lib/request_store/middleware.rb" line 9 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb" line 21 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb" line 22 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb" line 18 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb" line 120 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb" line 113 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb" line 518 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb" line 165 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/configuration.rb" line 227 in call
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb" line 561 in handle_request
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb" line 406 in process_client
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb" line 271 in block in run
File "/opt/www/frontend/code/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/thread_pool.rb" line 111 in block in spawn_thread
```

**Comment by ankane** [comment]
Shouldn't hurt to keep it consistent with `activerecord-session_store`. Thanks @codebreach and @ckassen.

**Comment by dylanjha** [comment]
FWIW I was running into this and this and the bug is no in ahoy, its in `rails_12factor`, or more specifically, `rails_stdout_logging`.

see:
* https://github.com/rails/rails/issues/24142
* https://github.com/heroku/rails_stdout_logging/pull/22

Easy solution for the moment is to either:

* remove `rails_12factor`
* use Rails 4.2.5 and wait for the `rails_stdout_logging` gem to be updated before upgrading to 4.2.6

**Comment by ankane** [comment]
Thanks for the info @dylanjha

**Comment by coreyward** [comment]
For anybody else that stumbles across this, `rails_stdout_logging` has an update (`v0.0.5`) that resolves the incompatibility. If you're using `rails_12factor`, you can get the updated `rails_stdout_logging` by running `bundle update rails_12factor`, even though the `rails_12factor` gem doesn't itself have any updates. 

Cheers!

**Pull request merged**
