### PR TITLE
Compatibility with Browser v2

### LINKED ISSUE #146: Gem `browser` updated to ver 2.0.0.
https://github.com/fnando/browser/issues/210

with browser gem ver 2.0.0.

An error occurs.

`undefined method downcase`

should use version 1.1.0. until solve it.

### PR DESCRIPTION
**Pull request by xuanxu**
Updates syntax to comply with new browser 2 version
Fixes #146

### CODE REVIEW

**Comment by cvd** [comment]
:+1:

**Comment by ankane** [comment]
Thanks for the pull request Jaunjo!  I think we should do this in a way that doesn't require users to upgrade browser.  Also, would be great to break this into multiple PRs for different features (for instance, memoized request params as a separate PR).

**Comment by xuanxu** [comment]
thanks for the reply @ankane!

1) I've created [a new PR](https://github.com/ankane/ahoy/pull/149) for the memoized params 

2) I don't see the need of "not require users to upgrade browser". That's the point of the PR, to update browser :) I think it is a harmless and simple upgrade. And if someone does not want to upgrade browser they can still use the current ahoy release, but can't imagine why someone would not want to.

**Comment by ankane** [comment]
The reason I didn't want to force users to upgrade is that they may be using browser in other places in the app.  However, it's probably not a huge deal.  Went with #152, as it was a bit cleaner.  Thanks again!

**Pull request closed without merging**
