### PR TITLE
Fix caching issues when trying to get DOM element's data-section attribute value

### PR DESCRIPTION
**Pull request by pazaricha**
### What I did
Instead of using jQuery's `.data` function, use the `.attr` function to prevent caching issue with elements that their data-section is changed dynamically.

#### How to reproduce the issue this solves:
1. Set data-section on any DOM element to some value. 
2. Click on it once.
3. Change it's data-section value to something else. 
4. Click on it again.
5. You will see that the second data-section you are getting in the event is the **old** data-section.

I already use this and it works perfectly.

### CODE REVIEW

**Comment by pazaricha** [comment]
@ankane Hey Andrew. This is basically the same PR as the one I did for ahoy.js here: https://github.com/ankane/ahoy.js/pull/20
Let me know if there is anything I need to change here.

**Comment by ankane** [comment]
Hey @pazaricha, same comment as https://github.com/ankane/ahoy.js/pull/20

**Comment by pazaricha** [comment]
@ankane DONE.:) also did it on the PR here: https://github.com/ankane/ahoy.js/pull/20

**Comment by ankane** [comment]
Looks good, thanks @pazaricha 👍

**Pull request merged**
